alias s="sudo su -"
alias gf="git fetch --prune"
alias gitgc="git remote prune origin && git repack && git prune-packed && git reflog expire --expire=1.month.ago && git gc --aggressive"
alias i="intellij"
alias tt="cd ~/projects/kirko/timbot"
alias hel="cd /home/robertk/projects/avocado_cust/ai/hel"
alias spinup="cd /home/robertk/projects/avocado_cust/ai/spinup"
alias blog="cd /home/robertk/projects/octopress"
alias blogup="cd /home/robertk/projects/octopress && vagrant up && vagrant ssh"
alias sno="cd ~/projects/kirko/backend" 
alias sno2="cd ~/projects/kirko-kube" 
alias hq="cd ~/projects/skyfii/skyfiihq"
alias nord="~/bin/skyfii/nordlayer.sh"
alias mybranch="cd ~/projects/skyfii/mybranch_skyfiihq"
alias hq2="cd ~/projects/skyfii/skyfii2/skyfiihq"
alias spa="cd ~/projects/skyfii/skyfii-io-platform-spa-ui && npm start"
alias runlocal="cd ~/projects/skyfii/skyfiihq && docker compose -p skyfiihq1 up zookeeper kafka mysql mongodb tokeniser_mongo elasticsearch redis"
alias downlocal="cd ~/projects/skyfii/skyfiihq && docker compose -p skyfiihq1 down -v"
alias runlocal_orig="cd ~/projects/skyfii/skyfiihq && docker compose -p skyfiihq1 -f docker-compose.yml up zookeeper kafka mysql mongodb elasticsearch kibana"
alias runsharded="cd ~/projects/skyfii/skyfiihq && docker compose -p skyfiihq1 -f docker-compose.yml up zookeeper kafka mysql elasticsearch kibana"
alias mongosharded="cd ~/projects/skyfii/skyfiihq && docker compose -p skyfiihq1 -f docker-compose-mongodb-sharded.yml up --scale mongodb-shard0=1 --scale mongodb-shard1=0 --scale mongodb-shard2=0"
alias terraform12=/usr/local/terraform/0.12.6/terraform
alias amm="echo amm-nologging; amm --no-remote-logging"
# skyfii kube envs
alias k9ss="source ~/bin/skyfii/kube/k9s-skyfii.sh"
alias aws-global="source ~/bin/skyfii/kube/aws-global-terraform.sh"
alias ae-live="source ~/bin/skyfii/kube/ae-live-kube.sh"
alias au-live="source ~/bin/skyfii/kube/au-live-kube.sh"
alias au-live-lite="source ~/bin/skyfii/kube/au-live-kube-lite.sh"
alias br-live="source ~/bin/skyfii/kube/br-live-kube.sh"
alias br-live-lite="source ~/bin/skyfii/kube/br-live-kube-lite.sh"
alias us2-live="source ~/bin/skyfii/kube/us2-live-kube.sh"
alias us2-live-lite="source ~/bin/skyfii/kube/us2-live-kube-lite.sh"
alias us2-staging="source ~/bin/skyfii/kube/us2-staging-kube.sh"
alias us2-staging-lite="source ~/skyfii/kube/bin/us2-staging-kube-lite.sh"
alias staging="source ~/bin/skyfii/kube/staging-kube.sh"
alias staging-lite="source ~/bin/skyfii/kube/staging-kube-lite.sh"
alias staging-x-1="source ~/bin/skyfii/kube/staging-x-1-kube.sh"
alias us-live="source ~/bin/skyfii/kube/us-live-kube.sh"
alias us-live-lite="source ~/bin/skyfii/kube/us-live-kube-lite.sh"
alias us-logs-live="source ~/bin/skyfii/kube/us-logs-live-kube.sh"
alias us-logs-live-lite="source ~/bin/skyfii/kube/us-logs-live-kube-lite.sh"
alias us-logs-staging="source ~/bin/skyfii/kube/us-logs-staging-kube.sh"
alias us-logs-staging-lite="source ~/bin/skyfii/kube/us-logs-staging-kube-lite.sh"
alias sg-live="source ~/bin/skyfii/kube/singapore-live-kube.sh"
alias sg-live-lite="source ~/bin/skyfii/kube/singapore-live-kube-lite.sh"
alias ie-live="source ~/bin/skyfii/kube/ireland-live-kube.sh"
alias ie-live-lite="source ~/bin/skyfii/kube/ireland-live-kube-lite.sh"
alias wf-live="source ~/bin/skyfii/kube/wf-live-kube.sh"
alias wf-live-lite="source ~/bin/skyfii/kube/wf-live-kube-lite.sh"
alias skyfiisec-aws-global="source ~/bin/skyfii/kube/skyfiisecaws-global-terraform.sh"
alias ie-sec="source ~/bin/skyfii/kube/skyfiisec-ie-sec-kube.sh"
alias terrafrom=terraform
alias tf=terraform

# aws-vault simplify usage
alias sso="asp skyfii-admin && aws sso login"
# uses aws sso
alias dev="aws-vault exec skyfii-dev"
alias dev_role="aws-vault exec Skyfii_ASSUME_DEVELOPER_MFA_ROLE"
# uses aws sso
alias admin="aws-vault exec skyfii-admin"
alias ds-admin="aws-vault exec skyfii-ds-admin"
alias admin_role="aws-vault exec Skyfii_ASSUME_ADMIN_MFA_ROLE"
alias awsdev="aws-vault exec Skyfii_ASSUME_DEVELOPER_MFA_ROLE -- aws"
alias awsadmin="aws-vault exec Skyfii_ASSUME_ADMIN_MFA_ROLE -- aws"
alias skyfiisec-admin="aws-vault exec skyfiisec_ASSUME_ADMIN_MFA_ROLE"
alias skyfiisec-ro="aws-vault exec skyfiisec_ASSUME_READ_ONLY_MFA_ROLE"
